// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQaOnu-6RkC43kpNIPo-ZEWjGzfbgiSu4',
    appId: '1:983634614786:web:6582769455423d7280651b',
    messagingSenderId: '983634614786',
    projectId: 'electric-bike-7e0e3',
    authDomain: 'electric-bike-7e0e3.firebaseapp.com',
    storageBucket: 'electric-bike-7e0e3.firebasestorage.app',
    measurementId: 'G-QKK5BMX3FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC54Wp03vm6teGKzV4ITQq1Q5yXU6xA9X0',
    appId: '1:983634614786:android:02b193f7429dbb6980651b',
    messagingSenderId: '983634614786',
    projectId: 'electric-bike-7e0e3',
    storageBucket: 'electric-bike-7e0e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47jbG3fphUJQeMbfsER-WpcrgfiN4wms',
    appId: '1:983634614786:ios:2f48f562fa0b19f880651b',
    messagingSenderId: '983634614786',
    projectId: 'electric-bike-7e0e3',
    storageBucket: 'electric-bike-7e0e3.firebasestorage.app',
    iosBundleId: 'com.example.testWindowsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC47jbG3fphUJQeMbfsER-WpcrgfiN4wms',
    appId: '1:983634614786:ios:2f48f562fa0b19f880651b',
    messagingSenderId: '983634614786',
    projectId: 'electric-bike-7e0e3',
    storageBucket: 'electric-bike-7e0e3.firebasestorage.app',
    iosBundleId: 'com.example.testWindowsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQaOnu-6RkC43kpNIPo-ZEWjGzfbgiSu4',
    appId: '1:983634614786:web:3d6bb6657adf09a980651b',
    messagingSenderId: '983634614786',
    projectId: 'electric-bike-7e0e3',
    authDomain: 'electric-bike-7e0e3.firebaseapp.com',
    storageBucket: 'electric-bike-7e0e3.firebasestorage.app',
    measurementId: 'G-63HPKGP46E',
  );
}
